import { Inconsolata } from "next/font/google";

import "@/styles/reset.css";
import "@/styles/global.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const josefinFont = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Secenory",
  description: "Generated by Secenory",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={josefinFont.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
