import { Inconsolata } from "next/font/google";

import "@/styles/reset.css";
import "@/styles/global.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import AuthProvider from "@/components/AuthProvider/AuthProvider";

const josefinFont = Inconsolata({ subsets: ["latin"] });

export const metadata = {
  title: "Secenory",
  description: "Generated by Secenory",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={josefinFont.className}>
      <body className="container">
        <AuthProvider>
          <Header />
          <main>{children}</main>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
