import { MoviesSection } from "@/components/movies-section";
import { search } from "@/services/general.service";
import React from "react";

//* Style
import styles from "./styles.module.css";

export const metadata = {
  title: "Search",
  description: "Generated by Secenory",
};

async function Search({ searchParams }) {
  console.log(" Search worked");
  const searchResultsPromise = search(searchParams.searchParams);

  const [{ results: searchResult }] = await Promise.all([searchResultsPromise]);
  return (
    <div className={searchResult.length > 0 ? "" : styles.wrapper}>
      {searchResult.length > 0 ? (
        <>
          <h1>Results for: {searchParams.searchParams}</h1>
          <MoviesSection movies={searchResult} />
        </>
      ) : (
        <div className={styles.notFound}>
          We couldn't find the result you were looking for :({" "}
        </div>
      )}
    </div>
  );
}

export default Search;
